name: PetNameFix
version: '${version}'
main: io.github.tanguygab.petnamefix.PetNameFix
api-version: '1.21.4'
authors: [ NEZNAMY, Tanguygab, Jim (AnEnragedPigeon) ]
description: A feature to disable minecraft feature making tamed animals with custom names copy NameTag properties of their owner.
